feat(zsh): allow different default remotes for git-sw (#6)
This allows for alternate remote names

Co-authored-by: Gibson Fahnestock <gibfahn@gmail.com>

diff --git a/dotfiles/bin/git-sw b/dotfiles/bin/git-sw
--- a/dotfiles/bin/git-sw
+++ b/dotfiles/bin/git-sw
@@ -2,14 +2,31 @@
 
 set -euo pipefail
 
+autoload -U colors && colors
+
+REMOTE_PRIMARY_NAME=${REMOTE_PRIMARY_NAME:-up}
+REMOTE_FORK_NAME=${REMOTE_FORK_NAME:-fork}
+
 usage() {
-echo "$(tput bold; tput setaf 74)$ZSH_ARGZERO [-h|--help] $(tput sgr0)
+echo "$(tput bold; tput setaf 74)$ZSH_ARGZERO [-h|--help] branch_name $(tput sgr0)
 
 git sw: switch to a branch, or create it, setting the upstream correctly.
+
+ENVIRONMENT VARIABLES:
+
+REMOTE_PRIMARY_NAME:
+    Name of the default remote. Usually the upstream remote vs a forked remote.
+    Default: up
+
+REMOTE_FORK_NAME:
+    Name of the forked remote (fork of the primary remote). Also applied as a prefix to
+    any forks of a non-primary remote. e.g. the fork of 'pub' would be 'pubfork'.
+    Default: fork
 "
 }
 
 main() {
+  [[ ${1:-} == "" ]] && { usage; error "branch_name argument is required"; }
   [[ ${1:-} =~ ^(--help|-h)$ ]] && { usage; exit; }
   [[ ${1:-} =~ ^(--version|-v)$ ]] && { echo "main"; exit; }
 
@@ -35,8 +52,8 @@ main() {
 
   # If we just created the branch and it's based on a fork branch, then update
   if [[ ${created:-} == 1 ]]; then
-    up_remote=$(up_remote || echo fork)
-    if [[ ${up_remote} == *fork* ]]; then
+    up_remote=$(up_remote || echo $REMOTE_FORK_NAME)
+    if [[ ${up_remote} == *${REMOTE_FORK_NAME}* ]]; then
       up_remote=$(up_remote_for_fork $up_remote)
       git branch -u $(default_remote_branch $up_remote)
     fi
@@ -47,10 +64,10 @@ main() {
 # Works out the up remote for the specified fork remote. I use `fork` for the fork of `up`,
 # otherwise I append `fork`, e.g. `pub` -> `pubfork`.
 up_remote_for_fork() {
-  if [[ $1 == fork ]]; then
-    echo up
+  if [[ $1 == $REMOTE_FORK_NAME ]]; then
+    echo $REMOTE_PRIMARY_NAME
   else
-    echo ${1%fork}
+    echo ${1%$REMOTE_FORK_NAME}
   fi
 }
 
@@ -61,6 +78,12 @@ default_remote_branch() {
 
 up_remote() {
   git rev-parse --abbrev-ref --symbolic-full-name @{u} | cut -d '/' -f 1
+}
+
+# Usage: exit message [rc]
+error() {
+  echo -e "${fg[red]}Error:${reset_color} $1" >&2
+  exit "${2:-1}"
 }
 
 main $@
