fix(zsh): write errors to stderr in scripts

diff --git a/dotfiles/bin/git-each b/dotfiles/bin/git-each
--- a/dotfiles/bin/git-each
+++ b/dotfiles/bin/git-each
@@ -74,8 +74,7 @@ $HOME/code"}}")
 
 # Usage: exit message [rc]
 error() {
-  # printf "${fg[red]}Error:${reset_color} %s\n" "$1"
-  echo -e "${fg[red]}Error:${reset_color} $1"
+  echo -e "${fg[red]}Error:${reset_color} $1" >&2
   exit "${2:-1}"
 }
 
diff --git a/dotfiles/bin/git-fork b/dotfiles/bin/git-fork
--- a/dotfiles/bin/git-fork
+++ b/dotfiles/bin/git-fork
@@ -148,8 +148,7 @@ clean_fork() {
 
 # Usage: exit message [rc]
 error() {
-  # printf "${fg[red]}Error:${reset_color} %s\n" "$1"
-  echo -e "${fg[red]}Error:${reset_color} $1"
+  echo -e "${fg[red]}Error:${reset_color} $1" >&2
   exit "${2:-1}"
 }
 
diff --git a/dotfiles/bin/hid b/dotfiles/bin/hid
--- a/dotfiles/bin/hid
+++ b/dotfiles/bin/hid
@@ -160,8 +160,7 @@ set_env_vars() {
 
 # Usage: exit message [rc]
 error() {
-  # printf "${fg[red]}Error:${reset_color} %s\n" "$1"
-  echo -e "${fg[red]}Error:${reset_color} $1"
+  echo -e "${fg[red]}Error:${reset_color} $1" >&2
   exit "${2:-1}"
 }
 
