fix(link): handle spaces in path, fix shellcheck complaints
Also adds a DRY_RUN=1 flag to see what the script would do, and removes
all dependencies.

diff --git a/link b/link
--- a/link
+++ b/link
@@ -1,5 +1,7 @@
 #!/bin/bash
 
+# shellcheck shell=bash disable=SC2059
+
 # This script symlinks everything from $FROMPATH (default: ./dotfiles/) into
 # $TOPATH (default: $HOME). Anything that would be overwritten is copied into
 # $BACKUP (default: $TOPATH/backup/).
@@ -9,43 +11,48 @@
 # example) you just edit ~/.bashrc, and as it's a symlink it'll actually edit
 # dotfiles/.bashrc. Then you can add and commit that change.
 
-. $(dirname $0)/helpers/colours.sh # Load helper script from dot/helpers.
+set -eu
 
+RED='\033[0;31m'    # Red.
+BBLACK='\033[1;30m' # Bright black (dark grey).
+NC='\033[0m'        # No Colour.
 
-: ${TOPATH:="$HOME"} # Where to write links to, update if necessary.
-: ${BACKUP:="$TOPATH/backup"} # Place to back up old files.
+: "${TOPATH:="$HOME"}"          # Where to write links to, update if necessary.
+: "${BACKUP:="$TOPATH/backup"}" # Place to back up old files.
 mkdir -p "$BACKUP"
 
-if [ -z "$FROMPATH" ]; then
-  cd "$(dirname $0)/dotfiles/"
+run_cmd=${DRY_RUN:+echo} # Set DRY_RUN to echo what we would do.
+
+if [ -z "${FROMPATH:-}" ]; then
+  cd "$(dirname "$0")/dotfiles/"
 else
   cd "$FROMPATH"
 fi
-: ${FROMPATH:="$PWD"} # Where you keep your dotfiles.
+: "${FROMPATH:="$PWD"}" # Where you keep your dotfiles.
 
 printf "❯❯❯ Updating dotfile symlinks (linking from path: $FROMPATH)\n\n"
 
-for FILE in $(find . -type f -o -type l | sed 's|./||'); do
-  mkdir -p "$TOPATH/$(dirname $FILE)"
-  if [ -d "$TOPATH/$FILE" -a ! -L "$TOPATH/$FILE" ]; then # Directory.
+while read -r FILE; do
+  $run_cmd mkdir -p "$TOPATH/$(dirname "$FILE")"
+  if [[ -d "$TOPATH/$FILE" && ! -L "$TOPATH/$FILE" ]]; then      # Directory.
     printf "${RED}DIRSKIP: $TOPATH/$FILE is a directory!${NC}\n" # This shouldn't happen.
     continue
   elif [ -L "$TOPATH/$FILE" ]; then # Symlink.
-    if [ "$(ls -l $TOPATH/$FILE | awk '{print $NF}')" = "$FROMPATH/$FILE" ]; then
+    if [ "$(readlink "$TOPATH/$FILE")" = "$FROMPATH/$FILE" ]; then
       printf "${BBLACK}SKIP: $TOPATH/$FILE already points to $FROMPATH/$FILE.${NC}\n"
       continue
     fi
-    printf "CHANGE: $TOPATH/$FILE $(ls -l $TOPATH/$FILE | awk '{print $NF}') -> $FROMPATH/$FILE\n"
-    mkdir -p "$BACKUP/$(dirname $FILE)"
-    rm "$TOPATH/$FILE" "$BACKUP/$FILE"
+    printf "CHANGE: '$TOPATH/$FILE' from '$(readlink "$TOPATH/$FILE")' -> '$FROMPATH/$FILE'\n"
+    $run_cmd mkdir -p "$BACKUP/$(dirname "$FILE")"
+    $run_cmd rm -f "$TOPATH/$FILE" "$BACKUP/$FILE"
   elif [ -e "$TOPATH/$FILE" ]; then # File.
-    printf "MOVE: $TOPATH/$FILE exists, moving to $BACKUP/$FILE\n"
-    mkdir -p "$BACKUP/$(dirname $FILE)"
-    mv "$TOPATH/$FILE" "$BACKUP/$FILE"
+    printf "MOVE: '$TOPATH/$FILE' exists, moving to '$BACKUP/$FILE'\n"
+    $run_cmd mkdir -p "$BACKUP/$(dirname "$FILE")"
+    $run_cmd mv "$TOPATH/$FILE" "$BACKUP/$FILE"
   else # Nothing there.
     printf "LINK: $TOPATH/$FILE -> $FROMPATH/$FILE\n"
   fi
-  ln -s "$FROMPATH/$FILE" "$TOPATH/$FILE"
-done
+  $run_cmd ln -s "$FROMPATH/$FILE" "$TOPATH/$FILE"
+done <<<"$(find . -type f -o -type l | sed 's|./||')"
 
-[ "$(ls -A $BACKUP)" ] || rm -r "$BACKUP" # Clean up backup folder if empty
+[[ "$(ls -A "$BACKUP")" ]] || $run_cmd rm -r "$BACKUP" # Clean up backup folder if empty
