refactor(up): update scripts to be clearer about skipping
Also fixes some inconsistencies in the different scripts.

diff --git a/scripts/run/computer_name b/scripts/run/computer_name
--- a/scripts/run/computer_name
+++ b/scripts/run/computer_name
@@ -4,6 +4,8 @@ set -euo pipefail
 
 set -x
 
+EXIT_CODE_SKIPPED=204 # up treats this exit code as "skipped"
+
 if [[ -n ${1:-} ]]; then
   mac_name=$1
 
@@ -32,17 +34,18 @@ year=$(grep -oE '[0-9]{4}' <<<$product_name)
 
 mac_name=$User-$mac_type-$year
 
-did_stuff= # Did we change anything?
+work_done= # Did we change anything?
 
 if [[ $(scutil --get LocalHostName) != $User-* ]]; then
-  did_stuff=yes
+  work_done=true
   scutil --set LocalHostName $mac_name
 fi
 
 if [[ $(scutil --get ComputerName) != $User-* ]]; then
-  did_stuff=yes
+  work_done=true
   scutil --set ComputerName $mac_name
 fi
 
-# Exit 204 to mark "skipped" if we didn't do anything.
-[[ -z ${did_stuff:-} ]] && exit 204 || true
+if [[ -z ${work_done:-} ]]; then
+  exit $EXIT_CODE_SKIPPED
+fi
diff --git a/scripts/run/hidutil b/scripts/run/hidutil
--- a/scripts/run/hidutil
+++ b/scripts/run/hidutil
@@ -7,6 +7,8 @@
 
 set -euxo pipefail
 
+EXIT_CODE_SKIPPED=204 # up treats this exit code as "skipped"
+
 work_done=
 
 from_path_hid=$dotfile_dir/bin/hid
@@ -42,5 +44,5 @@ if ! sudo launchctl list | grep -Fw co.fahn.gib.hidutil; then
 fi
 
 if [[ -z $work_done ]]; then
-  exit 204
+  exit "$EXIT_CODE_SKIPPED"
 fi
diff --git a/scripts/run/hosts b/scripts/run/hosts
--- a/scripts/run/hosts
+++ b/scripts/run/hosts
@@ -6,7 +6,9 @@ set -euo pipefail
 
 set -x
 
-[[ $USER == gib ]] || exit 204 # User is gib or we don't run.
+EXIT_CODE_SKIPPED=204 # up treats this exit code as "skipped"
+
+[[ $USER == gib ]] || exit "$EXIT_CODE_SKIPPED" # User is gib or we don't run.
 
 hosts=(
   # Block YouTube
@@ -56,5 +58,5 @@ if [[ -n $changed ]]; then
     *) echo "Not yet supported, fix $0" && exit 1 ;;
   esac
 else
-  exit 204
+  exit "$EXIT_CODE_SKIPPED"
 fi
diff --git a/scripts/run/login_items b/scripts/run/login_items
--- a/scripts/run/login_items
+++ b/scripts/run/login_items
@@ -2,8 +2,10 @@
 
 set -euxo pipefail
 
+EXIT_CODE_SKIPPED=204 # up treats this exit code as "skipped"
+
 # OS is darwin or we don't run.
-[[ $OSTYPE == darwin* ]] || exit 204
+[[ $OSTYPE == darwin* ]] || exit "$EXIT_CODE_SKIPPED"
 
 changed=
 
@@ -33,4 +35,6 @@ for item in "${current_login_items[@]}"; do
 done
 
 # If we didn't change anything, mark the task as skipped.
-[[ -n $changed ]] || exit 204
+if [[ -z $changed ]]; then
+  exit "$EXIT_CODE_SKIPPED"
+fi
diff --git a/scripts/run/mac_volume b/scripts/run/mac_volume
--- a/scripts/run/mac_volume
+++ b/scripts/run/mac_volume
@@ -6,6 +6,8 @@ set -euo pipefail
 
 set -x
 
+EXIT_CODE_SKIPPED="$EXIT_CODE_SKIPPED" # up treats this exit code as "skipped"
+
 shared_name=Shared-Data
 shared_volume=/Volumes/$shared_name
 
@@ -21,7 +23,7 @@ dirs_to_move=(
   ~/src
 )
 
-did_stuff=
+work_done=
 for dir in $dirs_to_move; do
   [[ -L $dir ]] && continue
 
@@ -31,7 +33,7 @@ for dir in $dirs_to_move; do
   # If directory not present skip it.
   if [[ ! -d $dir ]]; then
     if [[ -d $shared_dir ]]; then
-      did_stuff=yes
+      work_done=true
       ln -s $shared_dir $dir || sudo ln -s $shared_dir $dir
       continue
     else
@@ -39,7 +41,7 @@ for dir in $dirs_to_move; do
     fi
   fi
 
-  did_stuff=yes
+  work_done=true
   mkdir -p $(dirname $shared_dir)
   # If dir is owned by root (e.g. /opt/homebrew) then mv will complete, but deleting old dir will
   # fail, so delete just that empty dir (if it's truly empty) with `sudo rm -d`
@@ -48,5 +50,6 @@ for dir in $dirs_to_move; do
   ln -s $shared_dir $dir || sudo ln -s $shared_dir $dir
 done
 
-# Exit 204 to mark "skipped" if we didn't do anything.
-[[ -z ${did_stuff:-} ]] && exit 204 || true
+if [[ -z ${work_done:-} ]]; then
+  exit "$EXIT_CODE_SKIPPED"
+fi
diff --git a/scripts/run/tal_off b/scripts/run/tal_off
--- a/scripts/run/tal_off
+++ b/scripts/run/tal_off
@@ -2,16 +2,18 @@
 
 set -euo pipefail
 
+EXIT_CODE_SKIPPED=204 # up treats this exit code as "skipped"
+
 set -x
 
 # OS is darwin or we don't run.
-[[ $OSTYPE == darwin* ]] || exit 204
+[[ $OSTYPE == darwin* ]] || exit "$EXIT_CODE_SKIPPED"
 
 loginwindow_prefs=~/Library/Preferences/ByHost/com.apple.loginwindow*
 
 # If we can't find the file, we probably already nuked the preferences.
 if [[ ! -f $loginwindow_prefs ]]; then
-  exit 204
+  exit "$EXIT_CODE_SKIPPED"
 fi
 
 sudo chown root ~/Library/Preferences/ByHost/com.apple.loginwindow*
diff --git a/scripts/run_if/gpg b/scripts/run_if/gpg
--- a/scripts/run_if/gpg
+++ b/scripts/run_if/gpg
@@ -2,9 +2,11 @@
 
 set -eux
 
-which gpg || exit 204
+EXIT_CODE_SKIPPED=204 # up treats this exit code as "skipped"
+
+which gpg || exit "$EXIT_CODE_SKIPPED"
 
 # Run if gpg home missing, or gpg agent conf doesn't contain the expected values.
 if [ -d "$GNUPGHOME" ] && grep -q 'pinentry-program .*/pinentry-mac' "$GNUPGHOME"/gpg-agent.conf; then
-  exit 204
+  exit "$EXIT_CODE_SKIPPED"
 fi
diff --git a/scripts/run_if/wallpaper b/scripts/run_if/wallpaper
--- a/scripts/run_if/wallpaper
+++ b/scripts/run_if/wallpaper
@@ -2,8 +2,10 @@
 
 set -eux
 
-[ "$(uname)" = Darwin ] || exit 204
-[ "$(whoami)" = gib ] || exit 204
+EXIT_CODE_SKIPPED=204 # up treats this exit code as "skipped"
+
+[ "$(uname)" = Darwin ] || exit "$EXIT_CODE_SKIPPED"
+[ "$(whoami)" = gib ] || exit "$EXIT_CODE_SKIPPED"
 
 # Run if the desktop background is not already the one we set.
 backgrounds="$(osascript -e '
@@ -15,4 +17,4 @@ backgrounds="$(osascript -e '
 
 [ -z "$backgrounds" ] && exit 1
 
-echo "$backgrounds" | grep "$MAC_DESKTOP_BACKGROUND" && exit 204 || exit 0
+echo "$backgrounds" | grep "$MAC_DESKTOP_BACKGROUND" && exit "$EXIT_CODE_SKIPPED" || exit 0
