fix(login_items): add MacWhisper, allow optional apps to be in the list
This lets you install things, and have them added as login items if
needed.

diff --git a/scripts/run/login_items b/scripts/run/login_items
--- a/scripts/run/login_items
+++ b/scripts/run/login_items
@@ -18,6 +18,10 @@ done
 declare -p current_login_items wanted_login_items
 
 for item in "${wanted_login_items[@]}"; do
+  if [[ ! -e $item ]]; then
+    echo "Not adding missing login item $item" >&2
+    continue
+  fi
   if ! (( ${current_login_items[(I)$item]} )); then
     changed=true
     echo "Adding login item $item" >&2
