gibrc: handle crashes in shell upgrading
If something goes terribly wrong (like a segfault when you run zsh), if
you've used `exec` then you'll lose your terminal connection (bad when
you're sshing in).

However if you just run the other shell then you have to type `exit`
twice to get out of the session.

Get around this by exiting the parent shell if the child shell exited
with `0`, and log the error otherwise.

diff --git a/dotfiles/.config/gibrc b/dotfiles/.config/gibrc
--- a/dotfiles/.config/gibrc
+++ b/dotfiles/.config/gibrc
@@ -32,11 +32,11 @@ if [ "$ssh" -a "$GIBRC" = 0 -a "$shell" != zsh ]; then
   if exists zsh; then
     echo "Upgrading to zsh"
     export GIBRC=1
-    exec zsh # Replace existing shell with zsh.
+    zsh && exit || printf "\nERROR(gibrc): Zsh crashed with exit code: $?\n" # Replace existing shell with zsh.
   elif [ "$shell" != bash ] && exists bash; then
     echo "Upgrading to bash"
     export GIBRC=1
-    exec bash # Replace existing shell with bash.
+    bash && exit || printf "\nERROR(gibrc): Bash crashed with exit code: $?\n" # Replace existing shell with bash.
   fi
 fi
 
